### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by protoxx91** [sandoche/CuratedStack-nocode-template#44]
Hello, 

i get this error when i try to deploy : [Site deploy failed]

7:04:09 PM: npm ERR!       |   ^~~~~~~~~~~~~
7:04:09 PM: npm ERR! ../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
7:04:09 PM: npm ERR!   358 | NODE_MODULE(binding, RegisterModule);
7:04:09 PM: npm ERR!       | ^~~~~~~~~~~
7:04:09 PM: npm ERR! make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
7:04:09 PM: npm ERR! gyp ERR! build error
7:04:09 PM: npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
7:04:09 PM: npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/build/repo/node_modules/node-gyp/lib/build.js:262:23)
7:04:09 PM: npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
7:04:09 PM: npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
7:04:09 PM: npm ERR! gyp ERR! System Linux 5.4.228-131.415.amzn2.x86_64
7:04:09 PM: npm ERR! gyp ERR! command "/opt/buildhome/.nvm/versions/node/v16.19.1/bin/node" "/opt/build/repo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
7:04:09 PM: npm ERR! gyp ERR! cwd /opt/build/repo/node_modules/node-sass
7:04:09 PM: npm ERR! gyp ERR! node -v v16.19.1
7:04:09 PM: npm ERR! gyp ERR! node-gyp -v v3.8.0
7:04:09 PM: npm ERR! gyp ERR! not ok
7:04:09 PM: npm ERR! Build failed with error code: 1
7:04:09 PM: npm ERR! A complete log of this run can be found in:
7:04:09 PM: npm ERR!     /opt/buildhome/.npm/_logs/2023-03-24T18_02_13_045Z-debug-0.log
7:04:09 PM: Error during npm install
7:04:09 PM: Build was terminated: Build script returned non-zero exit code: 1
7:04:09 PM: Failing build: Failed to build site
7:04:09 PM: Finished processing build request in 2m2.398s

**Comment by wesleyclzns** [comment]
Mine was giving an error too, I need to install Python 2 and clear the cache about 2 times until it works.

the process was +-
```
npm install -g npm@latest
npm cache clean --force
npm rebuild node-gyp
npm uninstall node-sass
npm install node-sass
```
**but now I have a problem when I try to use npm run dev**

Cannot read properties of undefined (reading 'preset')                                                                      22:22:45  

  at nuxt.config.js:37:34
  at evalModule (node_modules\jiti\dist\jiti.js:1:247313)
  at jiti (node_modules\jiti\dist\jiti.js:1:245241)
  at Object.loadNuxtConfig (node_modules\@nuxt\config\dist\config.js:848:15)
  at loadNuxtConfig (node_modules\@nuxt\cli\dist\cli-index.js:295:32)
  at NuxtCommand.getNuxtConfig (node_modules\@nuxt\cli\dist\cli-index.js:397:26)
  at Object._listenDev (node_modules\@nuxt\cli\dist\cli-dev.js:63:30)
  at Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:49:25)
  at Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:44:16)
  at NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:356:22)


   ╭───────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                                                          │
   │   ✖ Nuxt Fatal Error                                                                                                                                                        │
   │                                                                                                                                                                                          │
   │   TypeError: Cannot read properties of undefined (reading 'preset')                                                                               │
   │                                                                                                                                                                                          │
   ╰───────────────────────────────────────────────────────────────────────╯
